# Generated by Django 5.0.7 on 2024-07-27 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="enrollment_date",
        ),
        migrations.RemoveField(
            model_name="student",
            name="parent_contact",
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="telegram_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Elementary", "Elementary"),
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Upper Intermediate", "Upper Intermediate"),
                    ("Advanced", "Advanced"),
                    ("Proficient", "Proficient"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
